language: python
python:
- '2.7'
- '3.6'
cache: pip
install:
- pip install -r requirements-tests.txt
- pip install -r requirements.txt
- pip install coveralls
script:
- python -m pytest --junitxml ./reports/results.xml --cov-config .coveragerc --cov=src
  .
after_success:
- coveralls
deploy:
  provider: pypi
  user: mlasevich
  password:
    secure: eduMc8F6ctoQ7STlpMXaVLi+25cU7HL+qUL+AMQrVoKJyZsJFzph9KKZ9r0KckWd5sFdVYm0OUlSIO2q5pP/eOLatlKEoRDiC6TOBbixkCeBD+ivs1cdAaCHxaFSbwNxAh2hW2gt2tEiPCL43bympieGxzYoU21zuYrnjkNQQuwJBN/MTDUlT42eqZF8bRZxfmBFxqt5wO2sdqUrudmq6H4efC11sktzkxzWX4vmXA0A++YonY5L2xxGxeYoUvwEFec/NQ6g450Ond8DyBMg7UmNDbZKiv2oXOi4oEVTkExEcRhEswOucS051DMZ6UkPa2KFcXg0FwZgzmTT9cWF+OoxihsPC/k7WrapQ77kngg64oX3xQHuAVGw+uZeZNxdTAmv7dxzkoJAXYrPjZPyKXDF6prAzNW9lZepU2Q7VoVkY3IpwoEJ0CdhX0E2xeXIa0/fnOsE5Xot+GC4pq7aHD4mZ2+lHMi1fEjHCk74bN/+fuiQcXe+PWDO1D0nRbcuXtfIL0yjjMlxNYx2hOMOxgwP8ZrzaNFqxzM5CW8dG3IUBPx0U7Wj5TCx/vvFyypRDWBNJ3t0rm/H8B1qqmT3lDOw0T8WyAwpGwLDIEYiTiCw0tBqox7iupcpQyGhGiv0oRo8Um6skruPYl1jDrKaQcYf8iq9ZD8HcSJxyyGKggw=
  skip_existing: true
  distributions: sdist bdist_wheel
  on:
    tags: true
